spring:
  # autoconfigure:
  #   exclude:
  #     - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  #     - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanager
    username: taskmanager_user
    password: taskmanager_password
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
